name: characters_coding_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.simpsons
    - .env.thewire
